# Generated by Django 5.2.3 on 2025-06-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language')),
                ('code', models.CharField(max_length=5, verbose_name='Language code')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200, verbose_name='Word')),
                ('translation', models.CharField(max_length=200, verbose_name='Translation')),
                ('from_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_lang', to='word.language')),
                ('to_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='word.language')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['source'],
            },
        ),
    ]
