# Generated by Django 5.2.3 on 2025-06-15 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(default='de', on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='word.language')),
                ('learn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='word.language')),
                ('ref_usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User setting',
                'verbose_name_plural': 'User settings',
            },
        ),
    ]
