# Generated by Django 5.2.3 on 2025-06-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_language'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='word.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='learn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learners', to='word.language', verbose_name='Learning Language'),
        ),
    ]
