# Generated by Django 5.2.3 on 2025-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_userprofile_language_alter_userprofile_learn'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exclude',
            field=models.ManyToManyField(related_name='excluded_by_user', to='word.word', verbose_name='Excluded Words'),
        ),
    ]
