# Generated by Django 5.2.3 on 2025-06-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_exclude'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='exclude',
            field=models.ManyToManyField(blank=True, related_name='excluded_by_user', to='word.word', verbose_name='Excluded Words'),
        ),
    ]
