# Generated by Django 5.2.3 on 2025-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_exclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='list_amount',
            field=models.PositiveIntegerField(default=20, help_text='Amount of words to show in the list', verbose_name='List Amount'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pair_amount',
            field=models.PositiveIntegerField(default=10, help_text='Amount of word pairs to show', verbose_name='Pair Amount'),
        ),
    ]
