# Generated by Django 6.0.5 on 2026-05-13 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_list_amount_userprofile_pair_amount'),
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='learn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learners', to='word.language', verbose_name='Learning Language'),
        ),
    ]
