# Generated by Django 6.0.5 on 2026-05-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userprofile_learn'),
        ('word', '0002_word_created_word_created_by_word_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='word.language', verbose_name='Source Language'),
        ),
    ]
