# Generated by Django 6.1 on 2026-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent_days',
            field=models.PositiveIntegerField(default=7, help_text='Amount of days to show in the recent words list', verbose_name='Recent Days'),
        ),
    ]
