# Generated by Django 6.0.8 on 2026-09-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_userprofile_recent_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='recent_days',
            field=models.PositiveIntegerField(default=30, help_text='Amount of days to show in the recent words list', verbose_name='Recent Days'),
        ),
    ]
